AllCops:
  Exclude:
    - 'spec/factory_spec.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
